version: '3.3'
services:
  #  nestjs_app:
  #    build:
  #      context: .
  #      Dockerfile: Dockerfile
  #    ports:
  #      - '3000:"3000'
  #    environment:
  #      - PORT=3000
  #      - NODE_ENV=production
  #    volumes:
  #      - ./src:/uer/src/app
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'nest_js'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
